# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7113ffc39247734fe9095773de9c630b"
name = "wishlist"
handle = "wishlist-742"
application_url = "https://abs-holdem-substances-male.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "petro-develop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_products,write_customers,write_products"

[auth]
redirect_urls = [
  "https://abs-holdem-substances-male.trycloudflare.com/auth/callback",
  "https://abs-holdem-substances-male.trycloudflare.com/auth/shopify/callback",
  "https://abs-holdem-substances-male.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[app_proxy]
url = "https://abs-holdem-substances-male.trycloudflare.com"
subpath = "wishlist"
prefix = "apps"

[pos]
embedded = false
